[CmdletBinding()]
param(
    [string]$Database = 'novel',

    [string]$ServerHost = '127.0.0.1',

    [int]$Port = 3306,

    [string]$User = 'root',

    [string]$Password = 'novel_root_password',

    [string]$MySqlDumpPath,

    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'lib\LitePackageTools.psm1') -Force

$defaults = Get-LitePackageDefaults -RepoRoot (Split-Path -Parent $PSScriptRoot)
$resolvedDumpPath = Resolve-MySqlDumpPath -ExplicitPath $MySqlDumpPath

if (-not $OutputPath) {
    $OutputPath = Join-Path $defaults.OutputDirectory 'seed-system-lite.sql'
}

$resolvedOutputPath = [System.IO.Path]::GetFullPath($OutputPath)
$outputDirectory = Split-Path -Parent $resolvedOutputPath
if (-not (Test-Path -LiteralPath $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}

$dumpArguments = @(
    '--default-character-set=utf8mb4',
    '--column-statistics=0',
    '--no-create-info',
    '--single-transaction',
    '--skip-lock-tables',
    '--skip-comments',
    '--skip-dump-date',
    '--skip-triggers',
    '--complete-insert',
    '-h', $ServerHost,
    '-P', $Port,
    '-u', $User,
    "--password=$Password",
    $Database
) + $defaults.SystemSeedTables

Write-Host "mysqldump: $resolvedDumpPath"
Write-Host "Output file: $resolvedOutputPath"
Write-Host "System seed tables: $($defaults.SystemSeedTables -join ', ')"

$dictionarySql = & $resolvedDumpPath @dumpArguments
if ($LASTEXITCODE -ne 0) {
    throw "System-seed dictionary export failed with exit code $LASTEXITCODE."
}

$demoAccountSql = New-LiteDemoAccountSql -Defaults $defaults
$content = @(
    '-- Generated by export-lite-system-seed.ps1'
    'SET NAMES utf8mb4;'
    ''
    $dictionarySql.TrimEnd()
    ''
    $demoAccountSql.Trim()
    ''
) -join [Environment]::NewLine

[System.IO.File]::WriteAllText($resolvedOutputPath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host 'System seed export completed.'
