[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [long[]]$NovelIds,

    [string]$Database = 'novel',

    [string]$ServerHost = '127.0.0.1',

    [int]$Port = 3306,

    [string]$User = 'root',

    [string]$Password = 'novel_root_password',

    [string]$MySqlDumpPath,

    [string]$OutputPath,

    [switch]$IncludeComments
)

$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'lib\LitePackageTools.psm1') -Force

$defaults = Get-LitePackageDefaults -RepoRoot (Split-Path -Parent $PSScriptRoot)
$resolvedDumpPath = Resolve-MySqlDumpPath -ExplicitPath $MySqlDumpPath

if (-not $OutputPath) {
    $OutputPath = Join-Path $defaults.OutputDirectory 'seed-reader-demo.sql'
}

$resolvedOutputPath = [System.IO.Path]::GetFullPath($OutputPath)
$outputDirectory = Split-Path -Parent $resolvedOutputPath
if (-not (Test-Path -LiteralPath $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}

$specs = Get-LiteReaderDemoDumpSpecs -NovelIds $NovelIds -IncludeComments:$IncludeComments
$sections = New-Object System.Collections.Generic.List[string]
$sections.Add('-- Generated by export-lite-reader-demo.ps1')
$sections.Add('SET NAMES utf8mb4;')
$sections.Add('')

Write-Host "mysqldump: $resolvedDumpPath"
Write-Host "Output file: $resolvedOutputPath"
Write-Host "Novel IDs: $((Join-SqlNumericList -Values $NovelIds))"

foreach ($spec in $specs) {
    $dumpArguments = @(
        '--default-character-set=utf8mb4',
        '--column-statistics=0',
        '--no-create-info',
        '--single-transaction',
        '--skip-lock-tables',
        '--skip-comments',
        '--skip-dump-date',
        '--skip-triggers',
        '--complete-insert',
        '-h', $ServerHost,
        '-P', $Port,
        '-u', $User,
        "--password=$Password"
    )

    if ($spec.HexBlob) {
        $dumpArguments += '--hex-blob'
    }

    $dumpArguments += @(
        $Database,
        $spec.Table,
        "--where=$($spec.Where)"
    )

    Write-Host "Exporting table '$($spec.Table)'..."
    $tableSql = & $resolvedDumpPath @dumpArguments
    if ($LASTEXITCODE -ne 0) {
        throw "Reader-demo export for table '$($spec.Table)' failed with exit code $LASTEXITCODE."
    }

    $sections.Add("-- Table: $($spec.Table)")
    $sections.Add($tableSql.TrimEnd())
    $sections.Add('')
}

[System.IO.File]::WriteAllText($resolvedOutputPath, ($sections -join [Environment]::NewLine), [System.Text.UTF8Encoding]::new($false))
Write-Host 'Reader demo export completed.'
